### PR TITLE
Include icon color in hexadecimal

### PR DESCRIPTION
**Pull request by foxt**

### CODE REVIEW

**Comment by foxt** [comment]
Darn eslint!

Check failed because I didn't order the keys alphabetically :skull:

**Review by haykam821 — CHANGES_REQUESTED** [review]
I’ll merge this if you fix the order of the keys ([`sort-keys`](https://eslint.org/docs/rules/sort-keys)) and remove transparency from the new value (because usually it is not needed).

**Comment by Hacksore** [comment]
👍

**Comment by foxt** [comment]
There we go, I fixed with an excess amount of commits @haykam821

**Review by haykam821 — APPROVED** [review]

**Comment by Hacksore** [comment]
@haykam821 Can you merge this?

**Pull request merged**
